spring:
  application:
    name: gateway

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

